import NodeTypesWO from "../../WorldObject/constants";

const NodeTypes = {
  CAMERA_ABSTRACT: "CAMERA_ABSTRACT",
  CAMERA_SPHERICAL_PATH: "CAMERA_SPHERICAL_PATH",
  CAMERA_ONE_EYE: "CAMERA_ONE_EYE",
  CAMERA_TWO_EYES: "CAMERA_TWO_EYES",
  ABSTRACT_LIGHT: "ABSTRACT_LIGHT",
  GLOWING_SPHERE: "GLOWING_SPHERE",
  GLOBAL_LIGHTING: "GLOBAL_LIGHTING",
  COMPOSITE_CUSTOM_SHAPES: "COMPOSITE_CUSTOM_SHAPES"
};

export default { ...NodeTypesWO, ...NodeTypes };
