const SceneSetterTypes = {
  CAMERA_SCENE_SETTER: "CAMERA_SCENE_SETTER",
  LIGHT_SCENE_SETTER: "LIGHT_SCENE_SETTER",
  GLOBAL_LIGHTING_SCENE_SETTER: "GLOBAL_LIGHTING_SCENE_SETTER"
};

export default SceneSetterTypes;
